export const personas =
    [{
        "id": 1,
        "first_name": "Desiree",
        "last_name": "Sawle",
        "email": "dsawle0@mayoclinic.com",
        "gender": "Female"
    }, {
        "id": 2,
        "first_name": "Tammi",
        "last_name": "Lakeland",
        "email": "tlakeland1@cbslocal.com",
        "gender": "Female"
    }, {
        "id": 3,
        "first_name": "Edgar",
        "last_name": "Bouchier",
        "email": "ebouchier2@wordpress.com",
        "gender": "Male"
    }, {
        "id": 4,
        "first_name": "Phedra",
        "last_name": "Hassall",
        "email": "phassall3@pagesperso-orange.fr",
        "gender": "Female"
    }, {
        "id": 5,
        "first_name": "Wynn",
        "last_name": "Riggulsford",
        "email": "wriggulsford4@ihg.com",
        "gender": "Male"
    }, {
        "id": 6,
        "first_name": "Ninon",
        "last_name": "Imms",
        "email": "nimms5@macromedia.com",
        "gender": "Female"
    }, {
        "id": 7,
        "first_name": "Giorgia",
        "last_name": "Denacamp",
        "email": "gdenacamp6@devhub.com",
        "gender": "Female"
    }, {
        "id": 8,
        "first_name": "Cristine",
        "last_name": "Cluckie",
        "email": "ccluckie7@wufoo.com",
        "gender": "Female"
    }, {
        "id": 9,
        "first_name": "Heinrick",
        "last_name": "Delhay",
        "email": "hdelhay8@biglobe.ne.jp",
        "gender": "Male"
    }, {
        "id": 10,
        "first_name": "Mata",
        "last_name": "Flewin",
        "email": "mflewin9@google.pl",
        "gender": "Male"
    }, {
        "id": 11,
        "first_name": "Kerry",
        "last_name": "Kingstne",
        "email": "kkingstnea@dmoz.org",
        "gender": "Male"
    }, {
        "id": 12,
        "first_name": "Darill",
        "last_name": "Blezard",
        "email": "dblezardb@japanpost.jp",
        "gender": "Male"
    }, {
        "id": 13,
        "first_name": "Juana",
        "last_name": "Rubinlicht",
        "email": "jrubinlichtc@zdnet.com",
        "gender": "Female"
    }, {
        "id": 14,
        "first_name": "Ingaberg",
        "last_name": "Tingley",
        "email": "itingleyd@japanpost.jp",
        "gender": "Female"
    }, {
        "id": 15,
        "first_name": "Neill",
        "last_name": "Isaksson",
        "email": "nisakssone@independent.co.uk",
        "gender": "Male"
    }, {
        "id": 16,
        "first_name": "Cynthy",
        "last_name": "Skeels",
        "email": "cskeelsf@omniture.com",
        "gender": "Female"
    }, {
        "id": 17,
        "first_name": "Aron",
        "last_name": "Arnopp",
        "email": "aarnoppg@reddit.com",
        "gender": "Male"
    }, {
        "id": 18,
        "first_name": "Renaldo",
        "last_name": "Veivers",
        "email": "rveiversh@shop-pro.jp",
        "gender": "Male"
    }, {
        "id": 19,
        "first_name": "Jimmy",
        "last_name": "Gerriet",
        "email": "jgerrieti@scientificamerican.com",
        "gender": "Male"
    }, {
        "id": 20,
        "first_name": "Odo",
        "last_name": "Whal",
        "email": "owhalj@unicef.org",
        "gender": "Male"
    }, {
        "id": 21,
        "first_name": "Hughie",
        "last_name": "Maciaszczyk",
        "email": "hmaciaszczykk@eventbrite.com",
        "gender": "Male"
    }, {
        "id": 22,
        "first_name": "Klarika",
        "last_name": "Paridge",
        "email": "kparidgel@dyndns.org",
        "gender": "Female"
    }, {
        "id": 23,
        "first_name": "Gustavus",
        "last_name": "Camplejohn",
        "email": "gcamplejohnm@narod.ru",
        "gender": "Male"
    }, {
        "id": 24,
        "first_name": "Poul",
        "last_name": "Shovelton",
        "email": "pshoveltonn@mediafire.com",
        "gender": "Male"
    }, {
        "id": 25,
        "first_name": "Janie",
        "last_name": "Batterham",
        "email": "jbatterhamo@fda.gov",
        "gender": "Female"
    }, {
        "id": 26,
        "first_name": "Franny",
        "last_name": "Coggon",
        "email": "fcoggonp@odnoklassniki.ru",
        "gender": "Female"
    }, {
        "id": 27,
        "first_name": "Sallee",
        "last_name": "Slocom",
        "email": "sslocomq@state.tx.us",
        "gender": "Female"
    }, {
        "id": 28,
        "first_name": "Tobin",
        "last_name": "Leist",
        "email": "tleistr@deliciousdays.com",
        "gender": "Male"
    }, {
        "id": 29,
        "first_name": "Bertrand",
        "last_name": "Berrey",
        "email": "bberreys@histats.com",
        "gender": "Male"
    }, {
        "id": 30,
        "first_name": "Harmon",
        "last_name": "Wyley",
        "email": "hwyleyt@marriott.com",
        "gender": "Male"
    }, {
        "id": 31,
        "first_name": "Sutherland",
        "last_name": "Kepe",
        "email": "skepeu@cafepress.com",
        "gender": "Male"
    }, {
        "id": 32,
        "first_name": "Agna",
        "last_name": "Arniz",
        "email": "aarnizv@berkeley.edu",
        "gender": "Female"
    }, {
        "id": 33,
        "first_name": "Kippie",
        "last_name": "Ziemecki",
        "email": "kziemeckiw@yahoo.com",
        "gender": "Male"
    }, {
        "id": 34,
        "first_name": "Theresita",
        "last_name": "Mockford",
        "email": "tmockfordx@merriam-webster.com",
        "gender": "Female"
    }, {
        "id": 35,
        "first_name": "Reynard",
        "last_name": "O'Bradain",
        "email": "robradainy@hc360.com",
        "gender": "Male"
    }, {
        "id": 36,
        "first_name": "Genovera",
        "last_name": "Agastina",
        "email": "gagastinaz@clickbank.net",
        "gender": "Female"
    }, {
        "id": 37,
        "first_name": "Mitchael",
        "last_name": "Kalinsky",
        "email": "mkalinsky10@cyberchimps.com",
        "gender": "Male"
    }, {
        "id": 38,
        "first_name": "Sile",
        "last_name": "Itzakson",
        "email": "sitzakson11@phoca.cz",
        "gender": "Female"
    }, {
        "id": 39,
        "first_name": "Chester",
        "last_name": "Glaum",
        "email": "cglaum12@prweb.com",
        "gender": "Male"
    }, {
        "id": 40,
        "first_name": "Jarred",
        "last_name": "Stockney",
        "email": "jstockney13@geocities.com",
        "gender": "Male"
    }, {
        "id": 41,
        "first_name": "Perl",
        "last_name": "Templeman",
        "email": "ptempleman14@ebay.com",
        "gender": "Female"
    }, {
        "id": 42,
        "first_name": "Garreth",
        "last_name": "Kinzett",
        "email": "gkinzett15@youtu.be",
        "gender": "Male"
    }, {
        "id": 43,
        "first_name": "Ira",
        "last_name": "Butters",
        "email": "ibutters16@cpanel.net",
        "gender": "Male"
    }, {
        "id": 44,
        "first_name": "Brook",
        "last_name": "Thursby",
        "email": "bthursby17@deviantart.com",
        "gender": "Male"
    }, {
        "id": 45,
        "first_name": "Talbot",
        "last_name": "Michie",
        "email": "tmichie18@illinois.edu",
        "gender": "Male"
    }, {
        "id": 46,
        "first_name": "Cornie",
        "last_name": "Jewer",
        "email": "cjewer19@github.io",
        "gender": "Male"
    }, {
        "id": 47,
        "first_name": "Kessia",
        "last_name": "O'Spillane",
        "email": "kospillane1a@mail.ru",
        "gender": "Female"
    }, {
        "id": 48,
        "first_name": "Tracy",
        "last_name": "Scandrite",
        "email": "tscandrite1b@lulu.com",
        "gender": "Female"
    }, {
        "id": 49,
        "first_name": "Basilius",
        "last_name": "Newcomb",
        "email": "bnewcomb1c@ning.com",
        "gender": "Male"
    }, {
        "id": 50,
        "first_name": "Jeannette",
        "last_name": "Baudino",
        "email": "jbaudino1d@goo.gl",
        "gender": "Female"
    }]

